name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install rpm packager for cargo
        run: cargo install cargo-rpm
      - name: Install deb packager for cargo
        run: cargo install cargo-deb

      - uses: actions/checkout@v2
      - name: Build generic Linux binary
        run: cargo build --verbose --release
      - name: Package Linux .deb
        run: cargo deb
      - name: Package Linux .rpm
        run: cargo rpm build -v

      - name: Run tests
        run: cargo test --verbose
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Install wix packager for cargo
        run: cargo install cargo-wix

      - uses: actions/checkout@v2
      - name: Build Windows binary
        run: cargo build --verbose --release
      - name: Build Windows installer
        run: cargo wix --verbose --nocapture
